### ISSUE TITLE
Docker deploy insecure?

### ISSUE THREAD

**Issue by crestenstclair** [circleci/docker-elasticsearch#1]
So, for this docker deploy, are you guys storing my unhashed username / password in order to do this deploy?

**Comment by bellkev** [comment]
As far as I'm aware, password authentication is the only way to login to Docker Hub, so we need to store those (environment variables configured in our UI are stored encrypted) in order to authenticate to Docker Hub. (There's an "auth" field saved in the `.dockercfg` file after you peform a `docker login`, but it's just "username:password" base64 encoded.) You can mitigate the risk of this by creating a dedicated deployment user on Docker Hub with minimal credentials and login as that user from CircleCI.

Our preference would definitely be that Docker Hub supported generating keys that can be easily revoked, but I don't think they do. Please let me know if you have more information on the topic.

You did make me realize that the README for this repo was out of sync with what's happening in the `circle.yml` file on this topic, so I just updated it accordingly.
